lang: en
name: Menstruation Project
title: Menstruation Project
# see https://ogp.me/#types
type: website
url: https://menstruation-project.org
image: https://static.wixstatic.com/media/09e476_b19147092b314de6bffbde17e342fa07~mv2_d_2853_1296_s_2.jpg/v1/crop/x_1160,y_336,w_522,h_602/fill/w_160,h_182,al_c,q_80,usm_0.66_1.00_0.01/MMAF_Header_Cover_logo.webp
description: An empowering documentary AND exhibition about the taboo territories of the feminine cycle.
