lang: en
name: Menstruation Project
title: Menstruation Project
# see https://ogp.me/#types
type: website
url: https://menstruation-project.com
image: https://res.cloudinary.com/tonipanoche/image/upload/v1620400406/menstruation-project/mp_background_home.jpg
description: The MENSTRUATION PROJECT raises awareness about beyond-gender menstruation as a gynecene phenomenon and focuses on artistic explorations of social, cultural and political layers of the cycle as a whole.
